import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import Database from 'better-sqlite3';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { BoardTrackerDatabase } from '../src/main/database';
import { testDatabase, companyInput, nonCashInput, positionInput } from './helpers';
import type { BoardTrackerDatabase as BoardTrackerDatabaseType } from '../src/main/database';
let db: BoardTrackerDatabaseType; let cleanup: () => void;
beforeEach(() => ({ db, cleanup } = testDatabase())); afterEach(() => cleanup());

describe('functionality: migrations and company CRUD', () => {
  it('creates versioned schema and seeded instrument types', () => { expect(db.db.prepare('SELECT version FROM schema_version ORDER BY version').all()).toHaveLength(4); expect(db.listInstrumentTypes().map((item) => item.name)).toEqual(['Options', 'Profits Interest', 'RSU', 'Stock', 'Warrant']); });
  it('re-running migration startup is idempotent', () => { db.close(); const file = (db.db as unknown as { name: string }).name; const next = new BoardTrackerDatabase(file); expect(next.db.prepare('SELECT version FROM schema_version').all()).toHaveLength(4); next.close(); });
  it('migrates an intact v0.1.0 database into the v0.2.0 schema', () => {
    const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'board-tracker-v010-')); const file = path.join(directory, 'legacy.db'); const legacy = new Database(file);
    legacy.exec(`CREATE TABLE schema_version (version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP); INSERT INTO schema_version(version) VALUES (1),(2); CREATE TABLE companies (id INTEGER PRIMARY KEY, name TEXT NOT NULL UNIQUE, business_summary TEXT, sector TEXT, website TEXT, board_size INTEGER, other_board_members TEXT, meeting_cadence TEXT, notes TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP); CREATE TABLE positions (id INTEGER PRIMARY KEY, company_id INTEGER NOT NULL, status TEXT NOT NULL, position_type TEXT NOT NULL, start_date TEXT, end_date TEXT, expected_decision_date TEXT, notes TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP); CREATE TABLE instrument_types (id INTEGER PRIMARY KEY, name TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP); CREATE TABLE compensation (id INTEGER PRIMARY KEY, position_id INTEGER NOT NULL, amount REAL NOT NULL, currency TEXT NOT NULL DEFAULT 'USD', frequency TEXT NOT NULL, notes TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP); INSERT INTO companies(id,name) VALUES (1,'Legacy Co'); INSERT INTO positions(id,company_id,status,position_type) VALUES (1,1,'current','advisor'); INSERT INTO instrument_types(id,name) VALUES (1,'Stock'); INSERT INTO compensation(id,position_id,amount,currency,frequency,notes) VALUES (1,1,1250,'USD','monthly','Legacy cash');`);
    legacy.close(); const migrated = new BoardTrackerDatabase(file);
    expect(migrated.db.prepare('SELECT version FROM schema_version ORDER BY version').pluck().all()).toEqual([1, 2, 3, 4]);
    const compensationColumns = migrated.db.prepare('PRAGMA table_info(compensation)').all() as Array<{ name: string; dflt_value: string | null }> ;
    expect(compensationColumns.map((column) => column.name)).toEqual(expect.arrayContaining(['type', 'instrument_type_id', 'quantity', 'grant_price', 'grant_date']));
    expect(compensationColumns.find((column) => column.name === 'type')?.dflt_value).toBe("'cash'");
    expect(migrated.db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='vesting_schedules'").pluck().get()).toBe('vesting_schedules');
    expect(migrated.db.prepare('PRAGMA table_info(vesting_schedules)').all().map((column: { name: string }) => column.name)).toEqual(expect.arrayContaining(['compensation_id', 'schedule_type', 'created_at', 'updated_at']));
    expect(migrated.db.prepare('SELECT type,amount,currency,frequency,notes FROM compensation WHERE id=1').get()).toEqual({ type: 'cash', amount: 1250, currency: 'USD', frequency: 'monthly', notes: 'Legacy cash' });
    migrated.close(); fs.rmSync(directory, { recursive: true, force: true });
  });
  it('creates and retrieves every company field', () => { const company = db.createCompany(companyInput()); expect(company).toMatchObject({ id: expect.any(Number), name: 'Example Corp', board_size: 7, meeting_cadence: 'Quarterly' }); expect(db.getCompany(company.id)?.other_board_members).toBe('Ada Lovelace'); });
  it('updates a company', () => { const company = db.createCompany(companyInput()); const updated = db.updateCompany(company.id, companyInput('Updated Corp')); expect(updated.name).toBe('Updated Corp'); expect(updated.position_count).toBe(0); });
  it('searches companies case-insensitively', () => { db.createCompany(companyInput('Alpha Company')); db.createCompany(companyInput('Beta LLC')); expect(db.listCompanies('ALPHA').map((company) => company.name)).toEqual(['Alpha Company']); });
  it('creates, updates, and deletes a position', () => { const company = db.createCompany(companyInput()); const position = db.createPosition(positionInput(company.id)); expect(position.status).toBe('current'); const changed = db.updatePosition(position.id, positionInput(company.id, { status: 'former', end_date: '2026-06-01' })); expect(changed.status).toBe('former'); db.deletePosition(position.id); expect(db.getCompany(company.id)?.positions).toHaveLength(0); });
  it('creates, updates, and deletes cash compensation', () => { const company = db.createCompany(companyInput()); const position = db.createPosition(positionInput(company.id)); const compensation = db.createCompensation({ position_id: position.id, amount: 2500, currency: 'usd', frequency: 'monthly', notes: 'Retainer' }); expect(compensation.currency).toBe('USD'); const changed = db.updateCompensation(compensation.id, { ...compensation, amount: 3000, frequency: 'monthly' }); expect(changed.amount).toBe(3000); db.deleteCompensation(compensation.id); expect(db.getCompany(company.id)?.positions[0].compensation).toHaveLength(0); });
  it('cascades positions and compensation when deleting a company', () => { const company = db.createCompany(companyInput()); const position = db.createPosition(positionInput(company.id)); db.createCompensation({ position_id: position.id, amount: 1000, frequency: 'annual' }); db.deleteCompany(company.id); expect(db.db.prepare('SELECT COUNT(*) FROM positions').pluck().get()).toBe(0); expect(db.db.prepare('SELECT COUNT(*) FROM compensation').pluck().get()).toBe(0); });
});

describe('functionality: non-cash compensation and vesting', () => {
  it('creates, updates, and deletes non-cash compensation', () => { const company = db.createCompany(companyInput()); const position = db.createPosition(positionInput(company.id)); const stock = db.listInstrumentTypes().find((item) => item.name === 'Stock')!; const compensation = db.createCompensation(nonCashInput(position.id, stock.id)); expect(compensation).toMatchObject({ type: 'non_cash', amount: null, quantity: 1000, instrument_type_id: stock.id, grant_price: 2.5 }); const updated = db.updateCompensation(compensation.id, nonCashInput(position.id, stock.id, { quantity: 1250, grant_price: null })); expect(updated).toMatchObject({ quantity: 1250, grant_price: null }); db.deleteCompensation(compensation.id); expect(db.getCompany(company.id)?.positions[0].compensation).toHaveLength(0); });
  it('creates, updates, and deletes an active vesting schedule', () => { const company = db.createCompany(companyInput()); const position = db.createPosition(positionInput(company.id)); const stock = db.listInstrumentTypes().find((item) => item.name === 'Stock')!; const compensation = db.createCompensation(nonCashInput(position.id, stock.id)); const schedule = db.createVestingSchedule({ compensation_id: compensation.id, schedule_type: 'cliff_linear', vesting_start: '2026-01-01', cliff_date: '2026-04-01', vesting_end: '2027-01-01', cadence: 'monthly', notes: 'Standard vesting' });
    expect(db.getCompany(company.id)?.positions[0].compensation[0].active_vesting_schedule?.id).toBe(schedule.id);
    const updated = db.updateVestingSchedule(schedule.id, { compensation_id: compensation.id, schedule_type: 'milestone', notes: 'After product launch' }); expect(updated).toMatchObject({ schedule_type: 'milestone', notes: 'After product launch', cliff_date: null });
    db.deleteVestingSchedule(schedule.id); expect(db.getCompany(company.id)?.positions[0].compensation[0].active_vesting_schedule).toBeNull();
  });
  it('keeps only the most recent vesting schedule active and clears schedules when changed to cash', () => { const company = db.createCompany(companyInput()); const position = db.createPosition(positionInput(company.id)); const stock = db.listInstrumentTypes().find((item) => item.name === 'Stock')!; const compensation = db.createCompensation(nonCashInput(position.id, stock.id)); db.createVestingSchedule({ compensation_id: compensation.id, schedule_type: 'custom', notes: 'Original award' }); const newer = db.createVestingSchedule({ compensation_id: compensation.id, schedule_type: 'immediate' }); expect(db.getCompany(company.id)?.positions[0].compensation[0].active_vesting_schedule?.id).toBe(newer.id); db.updateCompensation(compensation.id, { position_id: position.id, type: 'cash', amount: 50, currency: 'USD', frequency: 'monthly' }); expect(db.db.prepare('SELECT COUNT(*) FROM vesting_schedules WHERE compensation_id=?').pluck().get(compensation.id)).toBe(0); });
  it('regression: saves an immediate vesting schedule when the form sends empty strings instead of nulls for unrendered fields (bug reported in v0.2.0 - the UI never showed cliff/start/end/cadence fields for "Immediate", but still submitted them as empty strings, which failed enum validation and silently blocked every non-cash save since Immediate is the default schedule type)', () => {
    const company = db.createCompany(companyInput()); const position = db.createPosition(positionInput(company.id)); const stock = db.listInstrumentTypes().find((item) => item.name === 'Stock')!;
    const compensation = db.createCompensation(nonCashInput(position.id, stock.id));
    const schedule = db.createVestingSchedule({ compensation_id: compensation.id, schedule_type: 'immediate', cliff_date: '' as any, vesting_start: '' as any, vesting_end: '' as any, cadence: '' as any, notes: '' as any });
    expect(schedule).toMatchObject({ schedule_type: 'immediate', cliff_date: null, vesting_start: null, vesting_end: null, cadence: null, notes: null });
  });
});

describe('functionality: instrument types, seed import, and dashboard', () => {
  it('supports instrument type CRUD and blocks deletion while the type is used', () => { const created = db.createInstrumentType({ name: 'Phantom Units', description: 'Cash-settled award' }); expect(created.description).toBe('Cash-settled award'); const updated = db.updateInstrumentType(created.id, { name: 'Phantom Equity', description: '' }); expect(updated).toMatchObject({ name: 'Phantom Equity', description: null }); const company = db.createCompany(companyInput()); const position = db.createPosition(positionInput(company.id)); db.createCompensation(nonCashInput(position.id, created.id)); expect(() => db.deleteInstrumentType(created.id)).toThrow('in use'); db.deleteCompensation(db.getCompany(company.id)!.positions[0].compensation[0].id); db.deleteInstrumentType(created.id); expect(db.listInstrumentTypes().some((item) => item.id === created.id)).toBe(false); });
  const seeds = [{ name: 'Seed One', sector: 'AI', business_summary: 'one', website: 'one.test' }, { name: 'Seed Two', sector: 'Energy', business_summary: 'two', website: 'two.test' }];
  it('imports valid seed companies idempotently', () => { expect(db.importSeedCompanies(seeds)).toEqual({ inserted: 2, skipped: 0 }); expect(db.importSeedCompanies(seeds)).toEqual({ inserted: 0, skipped: 2 }); });
  it('calculates status counts and sorts potential decisions', () => { const company = db.createCompany(companyInput()); db.createPosition(positionInput(company.id, { status: 'current' })); const late = db.createPosition(positionInput(company.id, { status: 'potential', expected_decision_date: '2026-12-10' })); const early = db.createPosition(positionInput(company.id, { status: 'potential', expected_decision_date: '2026-10-10' })); expect(db.dashboard().counts).toEqual({ current: 1, former: 0, potential: 2 }); expect(db.dashboard().upcoming.map((position) => position.id)).toEqual([early.id, late.id]); });
  it('lists actively vesting awards by soonest vesting end', () => { const company = db.createCompany(companyInput()); const position = db.createPosition(positionInput(company.id)); const stock = db.listInstrumentTypes().find((item) => item.name === 'Stock')!; const first = db.createCompensation(nonCashInput(position.id, stock.id)); const second = db.createCompensation(nonCashInput(position.id, stock.id)); db.createVestingSchedule({ compensation_id: second.id, schedule_type: 'cliff_linear', vesting_start: '2026-01-01', cliff_date: '2026-01-01', vesting_end: '2026-01-20', cadence: 'monthly' }); db.createVestingSchedule({ compensation_id: first.id, schedule_type: 'cliff_linear', vesting_start: '2026-01-01', cliff_date: '2026-01-01', vesting_end: '2026-01-11', cadence: 'monthly' }); expect(db.dashboard('2026-01-06').upcoming_vesting.map((schedule) => schedule.compensation_id)).toEqual([first.id, second.id]); });
});
