import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { testDatabase, companyInput, positionInput } from './helpers';
import type { BoardTrackerDatabase } from '../src/main/database';
let db: BoardTrackerDatabase; let cleanup: () => void;
beforeEach(() => ({ db, cleanup } = testDatabase())); afterEach(() => cleanup());
describe('functionality: migrations and company CRUD', () => {
 it('creates versioned schema and common instrument type stubs', () => { expect(db.db.prepare('SELECT version FROM schema_version ORDER BY version').all()).toHaveLength(2); expect(db.db.prepare('SELECT name FROM instrument_types ORDER BY name').pluck().all()).toEqual(['Options','Profits Interest','RSU','Stock','Warrant']); });
 it('re-running migration startup is idempotent', () => { db.close(); const path = (db.db as unknown as { name: string }).name; const next = new (db.constructor as typeof BoardTrackerDatabase)(path); expect(next.db.prepare('SELECT version FROM schema_version').all()).toHaveLength(2); next.close(); });
 it('creates and retrieves every company field', () => { const company = db.createCompany(companyInput()); expect(company).toMatchObject({ id: expect.any(Number), name: 'Example Corp', board_size: 7, meeting_cadence: 'Quarterly' }); expect(db.getCompany(company.id)?.other_board_members).toBe('Ada Lovelace'); });
 it('updates a company', () => { const company = db.createCompany(companyInput()); const updated = db.updateCompany(company.id, companyInput('Updated Corp')); expect(updated.name).toBe('Updated Corp'); expect(updated.position_count).toBe(0); });
 it('searches companies case-insensitively', () => { db.createCompany(companyInput('Alpha Company')); db.createCompany(companyInput('Beta LLC')); expect(db.listCompanies('ALPHA').map((c) => c.name)).toEqual(['Alpha Company']); });
 it('creates, updates, and deletes a position', () => { const company = db.createCompany(companyInput()); const position = db.createPosition(positionInput(company.id)); expect(position.status).toBe('current'); const changed = db.updatePosition(position.id, positionInput(company.id, { status: 'former', end_date: '2026-06-01' })); expect(changed.status).toBe('former'); db.deletePosition(position.id); expect(db.getCompany(company.id)?.positions).toHaveLength(0); });
 it('creates, updates, and deletes cash compensation', () => { const company = db.createCompany(companyInput()); const position = db.createPosition(positionInput(company.id)); const compensation = db.createCompensation({ position_id: position.id, amount: 2500, currency: 'usd', frequency: 'monthly', notes: 'Retainer' }); expect(compensation.currency).toBe('USD'); const changed = db.updateCompensation(compensation.id, { ...compensation, amount: 3000, frequency: 'monthly' }); expect(changed.amount).toBe(3000); db.deleteCompensation(compensation.id); expect(db.getCompany(company.id)?.positions[0].compensation).toHaveLength(0); });
 it('cascades positions and compensation when deleting a company', () => { const company = db.createCompany(companyInput()); const position = db.createPosition(positionInput(company.id)); db.createCompensation({ position_id: position.id, amount: 1000, frequency: 'annual' }); db.deleteCompany(company.id); expect(db.db.prepare('SELECT COUNT(*) FROM positions').pluck().get()).toBe(0); expect(db.db.prepare('SELECT COUNT(*) FROM compensation').pluck().get()).toBe(0); });
});
describe('functionality: seed import and dashboard', () => {
 const seeds = [{ name: 'Seed One', sector: 'AI', business_summary: 'one', website: 'one.test' }, { name: 'Seed Two', sector: 'Energy', business_summary: 'two', website: 'two.test' }];
 it('imports valid seed companies', () => { expect(db.importSeedCompanies(seeds)).toEqual({ inserted: 2, skipped: 0 }); expect(db.listCompanies()).toHaveLength(2); });
 it('imports seed data idempotently', () => { db.importSeedCompanies(seeds); expect(db.importSeedCompanies(seeds)).toEqual({ inserted: 0, skipped: 2 }); });
 it('calculates status counts accurately', () => { const c = db.createCompany(companyInput()); db.createPosition(positionInput(c.id, { status: 'current' })); db.createPosition(positionInput(c.id, { status: 'former', position_type: 'advisor' })); db.createPosition(positionInput(c.id, { status: 'potential', position_type: 'advisory_board', expected_decision_date: '2026-10-02' })); expect(db.dashboard().counts).toEqual({ current: 1, former: 1, potential: 1 }); });
 it('sorts dated potential decisions before null dates', () => { const c = db.createCompany(companyInput()); const late = db.createPosition(positionInput(c.id, { status: 'potential', expected_decision_date: '2026-12-10' })); const early = db.createPosition(positionInput(c.id, { status: 'potential', expected_decision_date: '2026-10-10' })); const blank = db.createPosition(positionInput(c.id, { status: 'potential', expected_decision_date: null })); expect(db.dashboard().upcoming.map((p) => p.id)).toEqual([early.id, late.id, blank.id]); });
 it('clears expected decision date for non-potential positions', () => { const c = db.createCompany(companyInput()); const p = db.createPosition(positionInput(c.id, { status: 'current', expected_decision_date: '2026-10-10' })); expect(p.expected_decision_date).toBeNull(); });
});
