import { contextBridge, ipcRenderer } from 'electron';
import type { BoardTrackerApi } from '../shared/types';
const api: BoardTrackerApi = {
  dashboard: () => ipcRenderer.invoke('dashboard:get'),
  companies: { list: (search) => ipcRenderer.invoke('companies:list', search), get: (id) => ipcRenderer.invoke('companies:get', id), create: (input) => ipcRenderer.invoke('companies:create', input), update: (id, input) => ipcRenderer.invoke('companies:update', id, input), delete: (id) => ipcRenderer.invoke('companies:delete', id), copyResearchPrompt: (name, website) => ipcRenderer.invoke('companies:copy-research-prompt', name, website), addAlias: (id, name) => ipcRenderer.invoke('companies:add-alias', id, name), deleteAlias: (aliasId) => ipcRenderer.invoke('companies:delete-alias', aliasId) },
  positions: { create: (input) => ipcRenderer.invoke('positions:create', input), update: (id, input) => ipcRenderer.invoke('positions:update', id, input), delete: (id) => ipcRenderer.invoke('positions:delete', id) },
  compensation: { create: (input) => ipcRenderer.invoke('compensation:create', input), update: (id, input) => ipcRenderer.invoke('compensation:update', id, input), delete: (id) => ipcRenderer.invoke('compensation:delete', id) },
  instrumentTypes: { list: () => ipcRenderer.invoke('instrument-types:list'), create: (input) => ipcRenderer.invoke('instrument-types:create', input), update: (id, input) => ipcRenderer.invoke('instrument-types:update', id, input), delete: (id) => ipcRenderer.invoke('instrument-types:delete', id) },
  vestingSchedules: { create: (input) => ipcRenderer.invoke('vesting-schedules:create', input), update: (id, input) => ipcRenderer.invoke('vesting-schedules:update', id, input), delete: (id) => ipcRenderer.invoke('vesting-schedules:delete', id) },
  documents: { create: (input) => ipcRenderer.invoke('documents:create', input), update: (id, input) => ipcRenderer.invoke('documents:update', id, input), delete: (id) => ipcRenderer.invoke('documents:delete', id), pickFile: () => ipcRenderer.invoke('documents:pick-file'), open: (filePath) => ipcRenderer.invoke('documents:open', filePath) },
  deadlines: { list: (filter) => ipcRenderer.invoke('deadlines:list', filter ?? {}), create: (input) => ipcRenderer.invoke('deadlines:create', input), update: (id, input) => ipcRenderer.invoke('deadlines:update', id, input), delete: (id) => ipcRenderer.invoke('deadlines:delete', id), setCompleted: (id, completed) => ipcRenderer.invoke('deadlines:set-completed', id, completed) },
  importSeedData: () => ipcRenderer.invoke('seed:import'),
  extractedImport: { pickFile: () => ipcRenderer.invoke('extracted-import:pick-file'), preview: (contents, sourceLabel, selections) => ipcRenderer.invoke('extracted-import:preview', contents, sourceLabel, selections ?? {}), commit: (contents, sourceLabel, selections) => ipcRenderer.invoke('extracted-import:commit', contents, sourceLabel, selections ?? {}), batches: () => ipcRenderer.invoke('extracted-import:batches'), copyPrompt: () => ipcRenderer.invoke('extracted-import:copy-prompt'), saveSchema: () => ipcRenderer.invoke('extracted-import:save-schema') }
};
contextBridge.exposeInMainWorld('boardTracker', api);
