import Database from 'better-sqlite3';
import { runMigrations } from './migrations';
import { positiveId, validateCompensation, validateCompany, validatePosition, ValidationError } from './validation';
import type { Company, CompanyDetail, CompanyInput, Compensation, CompensationInput, DashboardData, Position, PositionInput } from '../shared/types';
export class BoardTrackerDatabase {
  readonly db: Database.Database;
  constructor(path: string) { this.db = new Database(path); this.db.pragma('foreign_keys = ON'); this.db.pragma('journal_mode = WAL'); runMigrations(this.db); }
  close(): void { this.db.close(); }
  private one<T>(sql: string, ...params: unknown[]): T { return this.db.prepare(sql).get(...params) as T; }
  private ensureChange(info: Database.RunResult, label: string): void { if (!info.changes) throw new ValidationError(`${label} was not found.`); }
  listCompanies(search = ''): Company[] { const term = typeof search === 'string' ? search.trim().slice(0, 200) : ''; return this.db.prepare(`SELECT c.*, COUNT(p.id) AS position_count FROM companies c LEFT JOIN positions p ON p.company_id=c.id WHERE c.name LIKE ? ESCAPE '\\' GROUP BY c.id ORDER BY c.name COLLATE NOCASE`).all(`%${term.replace(/[\\%_]/g, '\\$&')}%`) as Company[]; }
  getCompany(id: number): CompanyDetail | null { const company = this.db.prepare('SELECT c.*, COUNT(p.id) AS position_count FROM companies c LEFT JOIN positions p ON p.company_id=c.id WHERE c.id=? GROUP BY c.id').get(positiveId(id, 'Company')) as Company | undefined; if (!company) return null; const positions = this.db.prepare("SELECT * FROM positions WHERE company_id=? ORDER BY CASE status WHEN 'current' THEN 1 WHEN 'potential' THEN 2 ELSE 3 END, start_date DESC, id DESC").all(company.id) as Position[]; const byPosition = this.db.prepare('SELECT * FROM compensation WHERE position_id=? ORDER BY id DESC'); return { ...company, positions: positions.map((position) => ({ ...position, compensation: byPosition.all(position.id) as Compensation[] })) }; }
  createCompany(input: CompanyInput): Company { const v = validateCompany(input); try { const result = this.db.prepare('INSERT INTO companies (name,business_summary,sector,website,board_size,other_board_members,meeting_cadence,notes) VALUES (@name,@business_summary,@sector,@website,@board_size,@other_board_members,@meeting_cadence,@notes)').run(v); return this.getCompany(result.lastInsertRowid as number)!; } catch (error) { if (String(error).includes('UNIQUE')) throw new ValidationError('A company with this name already exists.'); throw error; } }
  updateCompany(id: number, input: CompanyInput): Company { const v = validateCompany(input); try { const result = this.db.prepare('UPDATE companies SET name=@name,business_summary=@business_summary,sector=@sector,website=@website,board_size=@board_size,other_board_members=@other_board_members,meeting_cadence=@meeting_cadence,notes=@notes,updated_at=CURRENT_TIMESTAMP WHERE id=@id').run({ ...v, id: positiveId(id, 'Company') }); this.ensureChange(result, 'Company'); return this.getCompany(id)!; } catch (error) { if (String(error).includes('UNIQUE')) throw new ValidationError('A company with this name already exists.'); throw error; } }
  deleteCompany(id: number): void { const result = this.db.prepare('DELETE FROM companies WHERE id=?').run(positiveId(id, 'Company')); this.ensureChange(result, 'Company'); }
  createPosition(input: PositionInput): Position { const v = validatePosition(input); const result = this.db.prepare('INSERT INTO positions(company_id,status,position_type,start_date,end_date,expected_decision_date,notes) VALUES (@company_id,@status,@position_type,@start_date,@end_date,@expected_decision_date,@notes)').run(v); return this.one<Position>('SELECT * FROM positions WHERE id=?', result.lastInsertRowid); }
  updatePosition(id: number, input: PositionInput): Position { const v = validatePosition(input); const result = this.db.prepare('UPDATE positions SET company_id=@company_id,status=@status,position_type=@position_type,start_date=@start_date,end_date=@end_date,expected_decision_date=@expected_decision_date,notes=@notes,updated_at=CURRENT_TIMESTAMP WHERE id=@id').run({ ...v, id: positiveId(id, 'Position') }); this.ensureChange(result, 'Position'); return this.one<Position>('SELECT * FROM positions WHERE id=?', id); }
  deletePosition(id: number): void { const result = this.db.prepare('DELETE FROM positions WHERE id=?').run(positiveId(id, 'Position')); this.ensureChange(result, 'Position'); }
  createCompensation(input: CompensationInput): Compensation { const v = validateCompensation(input); const result = this.db.prepare('INSERT INTO compensation(position_id,amount,currency,frequency,notes) VALUES (@position_id,@amount,@currency,@frequency,@notes)').run(v); return this.one<Compensation>('SELECT * FROM compensation WHERE id=?', result.lastInsertRowid); }
  updateCompensation(id: number, input: CompensationInput): Compensation { const v = validateCompensation(input); const result = this.db.prepare('UPDATE compensation SET position_id=@position_id,amount=@amount,currency=@currency,frequency=@frequency,notes=@notes,updated_at=CURRENT_TIMESTAMP WHERE id=@id').run({ ...v, id: positiveId(id, 'Compensation') }); this.ensureChange(result, 'Compensation'); return this.one<Compensation>('SELECT * FROM compensation WHERE id=?', id); }
  deleteCompensation(id: number): void { const result = this.db.prepare('DELETE FROM compensation WHERE id=?').run(positiveId(id, 'Compensation')); this.ensureChange(result, 'Compensation'); }
  dashboard(): DashboardData { const rows = this.db.prepare('SELECT status, COUNT(*) AS count FROM positions GROUP BY status').all() as {status: 'current'|'former'|'potential'; count: number}[]; const counts = { current: 0, former: 0, potential: 0 }; rows.forEach((row) => counts[row.status] = row.count); return { counts, upcoming: this.db.prepare("SELECT p.*, c.name AS company_name FROM positions p JOIN companies c ON c.id=p.company_id WHERE p.status='potential' ORDER BY p.expected_decision_date IS NULL, p.expected_decision_date ASC, c.name COLLATE NOCASE").all() as DashboardData['upcoming'] }; }
  importSeedCompanies(seed: unknown): { inserted: number; skipped: number } { if (!Array.isArray(seed)) throw new ValidationError('Seed data must be an array.'); const insert = this.db.prepare('INSERT OR IGNORE INTO companies(name,business_summary,sector,website) VALUES (@name,@business_summary,@sector,@website)'); let inserted = 0; let skipped = 0; this.db.transaction(() => seed.forEach((item) => { const i = item as Record<string, unknown>; const data = validateCompany({ name: i.name as string, business_summary: i.business_summary as string | null, sector: i.sector as string | null, website: i.website as string | null }); const result = insert.run(data); if (result.changes) inserted++; else skipped++; }))(); return { inserted, skipped }; }
}
