import { BrowserWindow, Menu, app, clipboard, dialog, ipcMain, shell } from 'electron';
import path from 'node:path';
import fs from 'node:fs';
import { BoardTrackerDatabase } from './database';
import { EXTRACTION_PROMPT } from '../shared/extraction-prompt';
import { IMPORT_JSON_SCHEMA_FILENAME, importJsonSchemaText } from '../shared/import-json-schema';
let database: BoardTrackerDatabase;
const seedPath = (): string => app.isPackaged ? path.join(process.resourcesPath, 'seed_data.json') : path.join(app.getAppPath(), 'assets', 'seed_data.json');
const importSeedData = (): { inserted: number; skipped: number } => database.importSeedCompanies(JSON.parse(fs.readFileSync(seedPath(), 'utf8')));
function createWindow(): void { const window = new BrowserWindow({ width: 1280, height: 820, minWidth: 960, minHeight: 640, title: 'Board Tracker', webPreferences: { preload: path.join(__dirname, '../preload/preload.js'), sandbox: true, contextIsolation: true, nodeIntegration: false } }); const devServer = process.env.VITE_DEV_SERVER_URL; if (devServer) window.loadURL(devServer); else window.loadFile(path.join(__dirname, '../renderer/index.html')); }
function registerHandlers(): void {
  ipcMain.handle('dashboard:get', () => database.dashboard());
  ipcMain.handle('companies:list', (_e, search?: string) => database.listCompanies(search)); ipcMain.handle('companies:get', (_e, id: number) => database.getCompany(id)); ipcMain.handle('companies:create', (_e, input) => database.createCompany(input)); ipcMain.handle('companies:update', (_e, id, input) => database.updateCompany(id, input)); ipcMain.handle('companies:delete', (_e, id) => database.deleteCompany(id));
  ipcMain.handle('positions:create', (_e, input) => database.createPosition(input)); ipcMain.handle('positions:update', (_e, id, input) => database.updatePosition(id, input)); ipcMain.handle('positions:delete', (_e, id) => database.deletePosition(id));
  ipcMain.handle('compensation:create', (_e, input) => database.createCompensation(input)); ipcMain.handle('compensation:update', (_e, id, input) => database.updateCompensation(id, input)); ipcMain.handle('compensation:delete', (_e, id) => database.deleteCompensation(id));
  ipcMain.handle('instrument-types:list', () => database.listInstrumentTypes()); ipcMain.handle('instrument-types:create', (_e, input) => database.createInstrumentType(input)); ipcMain.handle('instrument-types:update', (_e, id, input) => database.updateInstrumentType(id, input)); ipcMain.handle('instrument-types:delete', (_e, id) => database.deleteInstrumentType(id));
  ipcMain.handle('vesting-schedules:create', (_e, input) => database.createVestingSchedule(input)); ipcMain.handle('vesting-schedules:update', (_e, id, input) => database.updateVestingSchedule(id, input)); ipcMain.handle('vesting-schedules:delete', (_e, id) => database.deleteVestingSchedule(id));
  ipcMain.handle('documents:create', (_e, input) => database.createDocument(input)); ipcMain.handle('documents:update', (_e, id, input) => database.updateDocument(id, input)); ipcMain.handle('documents:delete', (_e, id) => database.deleteDocument(id));
  ipcMain.handle('documents:pick-file', async (event) => { const parent = BrowserWindow.fromWebContents(event.sender); const result = parent ? await dialog.showOpenDialog(parent, { properties: ['openFile'] }) : await dialog.showOpenDialog({ properties: ['openFile'] }); return result.canceled ? null : result.filePaths[0] ?? null; });
  ipcMain.handle('documents:open', async (_e, filePath: unknown) => { if (typeof filePath !== 'string' || !filePath.trim()) throw new Error('File path is required.'); const error = await shell.openPath(filePath); return error ? { ok: false, error } : { ok: true }; });
  ipcMain.handle('seed:import', () => importSeedData());
  ipcMain.handle('extracted-import:copy-prompt', () => { clipboard.writeText(EXTRACTION_PROMPT); return EXTRACTION_PROMPT; });
  ipcMain.handle('extracted-import:pick-file', async (event) => { const parent = BrowserWindow.fromWebContents(event.sender); const options: Electron.OpenDialogOptions = { properties: ['openFile'], filters: [{ name: 'Board Tracker import', extensions: ['json'] }] }; const result = parent ? await dialog.showOpenDialog(parent, options) : await dialog.showOpenDialog(options); const filePath = result.canceled ? null : result.filePaths[0] ?? null; if (!filePath) return null; const stats = fs.statSync(filePath); if (!stats.isFile()) throw new Error('The selected item is not a file.'); if (stats.size > 5 * 1024 * 1024) throw new Error('The import file must be 5 MB or smaller.'); return { file_path: filePath, file_name: path.basename(filePath), contents: fs.readFileSync(filePath, 'utf8') }; });
  ipcMain.handle('extracted-import:preview', (_e, contents: string, sourceLabel: string, selections) => database.previewExtractedImport(contents, sourceLabel, selections ?? {}));
  ipcMain.handle('extracted-import:commit', (_e, contents: string, sourceLabel: string, selections) => database.commitExtractedImport(contents, sourceLabel, selections ?? {}));
  ipcMain.handle('extracted-import:batches', () => database.listImportBatches());
  // Writes the JSON Schema out so it can be attached to the extraction session alongside the agreement.
  ipcMain.handle('extracted-import:save-schema', async (event) => { const parent = BrowserWindow.fromWebContents(event.sender); const options: Electron.SaveDialogOptions = { title: 'Save extraction schema', defaultPath: path.join(app.getPath('downloads'), IMPORT_JSON_SCHEMA_FILENAME), filters: [{ name: 'JSON Schema', extensions: ['json'] }] }; const result = parent ? await dialog.showSaveDialog(parent, options) : await dialog.showSaveDialog(options); if (result.canceled || !result.filePath) return null; fs.writeFileSync(result.filePath, importJsonSchemaText(), 'utf8'); return result.filePath; });
}
app.whenReady().then(() => { database = new BoardTrackerDatabase(path.join(app.getPath('userData'), 'board-tracker.db')); registerHandlers(); importSeedData(); Menu.setApplicationMenu(Menu.buildFromTemplate([{ label: 'File', submenu: [{ label: 'Import Seed Data', click: () => { importSeedData(); BrowserWindow.getAllWindows().forEach((window) => window.webContents.send('seed-imported')); } }, { role: 'quit' }] }, { label: 'View', submenu: [{ role: 'reload' }, { role: 'toggleDevTools' }] }])); createWindow(); app.on('activate', () => { if (!BrowserWindow.getAllWindows().length) createWindow(); }); });
app.on('window-all-closed', () => { if (process.platform !== 'darwin') app.quit(); }); app.on('before-quit', () => database?.close());
