import type Database from 'better-sqlite3';
const migrations = [
`CREATE TABLE IF NOT EXISTS companies (id INTEGER PRIMARY KEY, name TEXT NOT NULL UNIQUE, business_summary TEXT, sector TEXT, website TEXT, board_size INTEGER, other_board_members TEXT, meeting_cadence TEXT, notes TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
 CREATE TABLE IF NOT EXISTS positions (id INTEGER PRIMARY KEY, company_id INTEGER NOT NULL, status TEXT NOT NULL CHECK(status IN ('current','former','potential')), position_type TEXT NOT NULL CHECK(position_type IN ('governing_board','advisory_board','advisor')), start_date TEXT, end_date TEXT, expected_decision_date TEXT, notes TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(company_id) REFERENCES companies(id) ON DELETE CASCADE);
 CREATE TABLE IF NOT EXISTS compensation (id INTEGER PRIMARY KEY, position_id INTEGER NOT NULL, amount REAL NOT NULL, currency TEXT NOT NULL DEFAULT 'USD', frequency TEXT NOT NULL CHECK(frequency IN ('one_time','annual','quarterly','monthly','per_meeting')), notes TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(position_id) REFERENCES positions(id) ON DELETE CASCADE);
 CREATE TABLE IF NOT EXISTS instrument_types (id INTEGER PRIMARY KEY, name TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
 CREATE INDEX IF NOT EXISTS idx_positions_company ON positions(company_id); CREATE INDEX IF NOT EXISTS idx_positions_status_decision ON positions(status, expected_decision_date); CREATE INDEX IF NOT EXISTS idx_compensation_position ON compensation(position_id);`,
`INSERT OR IGNORE INTO instrument_types(name) VALUES ('Stock'), ('Options'), ('RSU'), ('Warrant'), ('Profits Interest');`,
`CREATE TABLE compensation_v2 (id INTEGER PRIMARY KEY, position_id INTEGER NOT NULL, type TEXT NOT NULL DEFAULT 'cash' CHECK(type IN ('cash','non_cash')), amount REAL, currency TEXT, frequency TEXT CHECK(frequency IS NULL OR frequency IN ('one_time','annual','quarterly','monthly','per_meeting')), instrument_type_id INTEGER, quantity REAL, grant_price REAL, grant_date TEXT, notes TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(position_id) REFERENCES positions(id) ON DELETE CASCADE, FOREIGN KEY(instrument_type_id) REFERENCES instrument_types(id) ON DELETE RESTRICT, CHECK((type='cash' AND amount IS NOT NULL AND currency IS NOT NULL AND frequency IS NOT NULL AND instrument_type_id IS NULL AND quantity IS NULL) OR (type='non_cash' AND amount IS NULL AND currency IS NULL AND frequency IS NULL AND instrument_type_id IS NOT NULL AND quantity IS NOT NULL)));
 INSERT INTO compensation_v2 (id,position_id,type,amount,currency,frequency,notes,created_at,updated_at) SELECT id,position_id,'cash',amount,currency,frequency,notes,created_at,updated_at FROM compensation;
 DROP TABLE compensation;
 ALTER TABLE compensation_v2 RENAME TO compensation;
 CREATE INDEX IF NOT EXISTS idx_compensation_position ON compensation(position_id);
 CREATE INDEX IF NOT EXISTS idx_compensation_instrument_type ON compensation(instrument_type_id);
 ALTER TABLE instrument_types ADD COLUMN description TEXT;`,
`CREATE TABLE IF NOT EXISTS vesting_schedules (id INTEGER PRIMARY KEY, compensation_id INTEGER NOT NULL, schedule_type TEXT NOT NULL CHECK(schedule_type IN ('immediate','cliff_linear','milestone','custom')), cliff_date TEXT, vesting_start TEXT, vesting_end TEXT, cadence TEXT CHECK(cadence IS NULL OR cadence IN ('monthly','quarterly','annual','one_time')), notes TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(compensation_id) REFERENCES compensation(id) ON DELETE CASCADE);
 CREATE INDEX IF NOT EXISTS idx_vesting_schedules_compensation ON vesting_schedules(compensation_id);`,
`CREATE TABLE IF NOT EXISTS documents (id INTEGER PRIMARY KEY, company_id INTEGER NOT NULL, position_id INTEGER, compensation_id INTEGER, document_type TEXT NOT NULL, file_path TEXT, file_name TEXT, description TEXT, document_date TEXT, status TEXT NOT NULL CHECK(status IN ('linked','missing')), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(company_id) REFERENCES companies(id) ON DELETE CASCADE, FOREIGN KEY(position_id) REFERENCES positions(id) ON DELETE SET NULL, FOREIGN KEY(compensation_id) REFERENCES compensation(id) ON DELETE SET NULL, CHECK((status='linked' AND file_path IS NOT NULL) OR (status='missing' AND file_path IS NULL)));
 CREATE INDEX IF NOT EXISTS idx_documents_company ON documents(company_id);
 CREATE INDEX IF NOT EXISTS idx_documents_position ON documents(position_id);
 CREATE INDEX IF NOT EXISTS idx_documents_compensation ON documents(compensation_id);
 CREATE INDEX IF NOT EXISTS idx_documents_status_company ON documents(status, company_id);`
];
export function runMigrations(db: Database.Database): void { db.exec('CREATE TABLE IF NOT EXISTS schema_version (version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)'); const applied = new Set((db.prepare('SELECT version FROM schema_version').all() as { version: number }[]).map((row) => row.version)); migrations.forEach((sql, index) => { const version = index + 1; if (!applied.has(version)) db.transaction(() => { db.exec(sql); db.prepare('INSERT INTO schema_version(version) VALUES (?)').run(version); })(); }); }
