import type Database from 'better-sqlite3';
const migrations = [
`CREATE TABLE IF NOT EXISTS companies (id INTEGER PRIMARY KEY, name TEXT NOT NULL UNIQUE, business_summary TEXT, sector TEXT, website TEXT, board_size INTEGER, other_board_members TEXT, meeting_cadence TEXT, notes TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
 CREATE TABLE IF NOT EXISTS positions (id INTEGER PRIMARY KEY, company_id INTEGER NOT NULL, status TEXT NOT NULL CHECK(status IN ('current','former','potential')), position_type TEXT NOT NULL CHECK(position_type IN ('governing_board','advisory_board','advisor')), start_date TEXT, end_date TEXT, expected_decision_date TEXT, notes TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(company_id) REFERENCES companies(id) ON DELETE CASCADE);
 CREATE TABLE IF NOT EXISTS compensation (id INTEGER PRIMARY KEY, position_id INTEGER NOT NULL, amount REAL NOT NULL, currency TEXT NOT NULL DEFAULT 'USD', frequency TEXT NOT NULL CHECK(frequency IN ('one_time','annual','quarterly','monthly','per_meeting')), notes TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(position_id) REFERENCES positions(id) ON DELETE CASCADE);
 CREATE TABLE IF NOT EXISTS instrument_types (id INTEGER PRIMARY KEY, name TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
 CREATE INDEX IF NOT EXISTS idx_positions_company ON positions(company_id); CREATE INDEX IF NOT EXISTS idx_positions_status_decision ON positions(status, expected_decision_date); CREATE INDEX IF NOT EXISTS idx_compensation_position ON compensation(position_id);`,
`INSERT OR IGNORE INTO instrument_types(name) VALUES ('Stock'), ('Options'), ('RSU'), ('Warrant'), ('Profits Interest');`
];
export function runMigrations(db: Database.Database): void { db.exec('CREATE TABLE IF NOT EXISTS schema_version (version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)'); const applied = new Set((db.prepare('SELECT version FROM schema_version').all() as { version: number }[]).map((row) => row.version)); migrations.forEach((sql, index) => { const version = index + 1; if (!applied.has(version)) db.transaction(() => { db.exec(sql); db.prepare('INSERT INTO schema_version(version) VALUES (?)').run(version); })(); }); }
