import type { CompensationInput, CompanyInput, PositionInput } from '../shared/types';
export class ValidationError extends Error { constructor(message: string) { super(message); this.name = 'ValidationError'; } }
const lengths = { name: 200, sector: 150, website: 2048, summary: 10000, members: 5000, cadence: 100, notes: 10000, currency: 3 };
const nullableText = (value: unknown, field: string, max: number): string | null => { if (value == null) return null; if (typeof value !== 'string') throw new ValidationError(`${field} must be text.`); const clean = value.trim(); if (clean.length > max) throw new ValidationError(`${field} must be ${max} characters or fewer.`); return clean || null; };
const requiredText = (value: unknown, field: string, max: number): string => { const clean = nullableText(value, field, max); if (!clean) throw new ValidationError(`${field} is required.`); return clean; };
const validDate = (value: unknown, field: string): string | null => { if (value == null || value === '') return null; if (typeof value !== 'string' || !/^\d{4}-\d{2}-\d{2}$/.test(value)) throw new ValidationError(`${field} must be a valid YYYY-MM-DD date.`); const parsed = new Date(`${value}T00:00:00Z`); if (Number.isNaN(parsed.getTime()) || parsed.toISOString().slice(0, 10) !== value) throw new ValidationError(`${field} must be a valid calendar date.`); return value; };
export const positiveId = (value: unknown, field: string): number => { if (!Number.isInteger(value) || (value as number) < 1) throw new ValidationError(`${field} must be a valid record id.`); return value as number; };
export function validateCompany(input: CompanyInput): Required<CompanyInput> { const boardSize = input.board_size == null || input.board_size === ('' as never) ? null : input.board_size; if (boardSize !== null && (!Number.isInteger(boardSize) || boardSize < 0 || boardSize > 100000)) throw new ValidationError('Board size must be a whole number between 0 and 100,000.'); return { name: requiredText(input.name, 'Company name', lengths.name), business_summary: nullableText(input.business_summary, 'Business summary', lengths.summary), sector: nullableText(input.sector, 'Sector', lengths.sector), website: nullableText(input.website, 'Website', lengths.website), board_size: boardSize, other_board_members: nullableText(input.other_board_members, 'Other board members', lengths.members), meeting_cadence: nullableText(input.meeting_cadence, 'Meeting cadence', lengths.cadence), notes: nullableText(input.notes, 'Notes', lengths.notes) }; }
export function validatePosition(input: PositionInput): Required<PositionInput> { const company_id = positiveId(input.company_id, 'Company'); if (!['current', 'former', 'potential'].includes(input.status)) throw new ValidationError('Status is invalid.'); if (!['governing_board', 'advisory_board', 'advisor'].includes(input.position_type)) throw new ValidationError('Position type is invalid.'); const start_date = validDate(input.start_date, 'Start date'); const end_date = validDate(input.end_date, 'End date'); const expected_decision_date = validDate(input.expected_decision_date, 'Expected decision date'); if (start_date && end_date && end_date < start_date) throw new ValidationError('End date cannot be before start date.'); return { company_id, status: input.status, position_type: input.position_type, start_date, end_date, expected_decision_date: input.status === 'potential' ? expected_decision_date : null, notes: nullableText(input.notes, 'Notes', lengths.notes) }; }
export function validateCompensation(input: CompensationInput): Required<CompensationInput> { const position_id = positiveId(input.position_id, 'Position'); if (typeof input.amount !== 'number' || !Number.isFinite(input.amount) || input.amount <= 0 || input.amount > 1_000_000_000_000) throw new ValidationError('Amount must be greater than zero and no more than 1,000,000,000,000.'); const currency = requiredText(input.currency ?? 'USD', 'Currency', lengths.currency).toUpperCase(); if (!/^[A-Z]{3}$/.test(currency)) throw new ValidationError('Currency must be a three-letter ISO code.'); if (!['one_time', 'annual', 'quarterly', 'monthly', 'per_meeting'].includes(input.frequency)) throw new ValidationError('Frequency is invalid.'); return { position_id, amount: input.amount, currency, frequency: input.frequency, notes: nullableText(input.notes, 'Notes', lengths.notes) }; }
